spring.application.name=dern
spring.datasource.url=jdbc:postgresql://ep-silent-meadow-a1h3xbzp-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_1qfPiLtSDJv5&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1qfPiLtSDJv5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect