spring.application.name=dern
spring.datasource.url=jdbc:postgresql://db.yecswdyhrxsjvjjpyygg.supabase.co:5432/postgres?user=postgres&password=sWsC#2312#ma
spring.datasource.username=postgres
spring.datasource.password=sWsC#2312#ma

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080