spring.application.name=dern
spring.datasource.url=jdbc:postgresql://ep-mute-brook-a1c5qxii-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_jWRgaD8Co4kr&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jWRgaD8Co4kr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect